In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [6]:
df=pd.read_csv("Advertising.csv")
df


,TV,radio,newspaper,sales
0,230.1,37.8,69.2,22.1
1,44.5,39.3,45.1,10.4
2,17.2,45.9,69.3,9.3
3,151.5,41.3,58.5,18.5
4,180.8,10.8,58.4,12.9
...,...,...,...,...
195,38.2,3.7,13.8,7.6
196,94.2,4.9,8.1,9.7
197,177.0,9.3,6.4,12.8
198,283.6,42.0,66.2,25.5


In [7]:
X=df.drop("sales",axis=1)
y=df["sales"]

In [8]:
from sklearn.preprocessing import PolynomialFeatures

poly_converter=PolynomialFeatures(degree=3,include_bias=False)

poly_converter.fit(X)

,degree,3
,interaction_only,False
,include_bias,False
,order,'C'


In [9]:
poly_features=poly_converter.transform(X)

In [10]:
poly_features

array([[2.30100000e+02, 3.78000000e+01, 6.92000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [4.45000000e+01, 3.93000000e+01, 4.51000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.72000000e+01, 4.59000000e+01, 6.93000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.77000000e+02, 9.30000000e+00, 6.40000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [2.83600000e+02, 4.20000000e+01, 6.62000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [2.32100000e+02, 8.60000000e+00, 8.70000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]], shape=(200, 19))

In [11]:
np.random.seed(101)
from sklearn.model_selection import train_test_split


X_train,X_test,y_train,y_test=train_test_split(poly_features,y,test_size=0.3)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()

In [14]:
scaler.fit(X_train)

,copy,True
,with_mean,True
,with_std,True


In [15]:
X_train=scaler.transform(X_train)

In [16]:
X_test=scaler.transform(X_test)
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [17]:
from sklearn.linear_model import Ridge

ridge_model=Ridge(alpha=10)
ridge_model.fit(X_train,y_train)

,alpha,10
,fit_intercept,True
,copy_X,True
,max_iter,None
,tol,0.0001
,solver,'auto'
,positive,False
,random_state,None


In [18]:
test_predictions=ridge_model.predict(X_test)

In [19]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [20]:
MAE=mean_absolute_error(y_test,test_predictions)

In [21]:
MSE=mean_squared_error(y_test,test_predictions)

In [22]:
MAE

0.5774404204714181

In [23]:
RMSE=np.sqrt(MSE)

In [24]:
RMSE

np.float64(0.8946386461319682)

In [25]:
from sklearn.linear_model import RidgeCV

In [26]:
ridge_cv_model=RidgeCV(alphas=(0.1,1.0,10.0),scoring='neg_mean_absolute_error')

In [27]:
ridge_cv_model.fit(X_train,y_train)

,alphas,"(0.1, ...)"
,fit_intercept,True
,scoring,'neg_mean_absolute_error'
,cv,None
,gcv_mode,None
,store_cv_results,False
,alpha_per_target,False


In [28]:
ridge_cv_model.alpha_

np.float64(0.1)

In [29]:
from sklearn.metrics import get_scorer_names,get_scorer

print(get_scorer_names())

['accuracy', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'average_precision', 'balanced_accuracy', 'completeness_score', 'd2_absolute_error_score', 'explained_variance', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'fowlkes_mallows_score', 'homogeneity_score', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted', 'matthews_corrcoef', 'mutual_info_score', 'neg_brier_score', 'neg_log_loss', 'neg_max_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_gamma_deviance', 'neg_mean_poisson_deviance', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_median_absolute_error', 'neg_negative_likelihood_ratio', 'neg_root_mean_squared_error', 'neg_root_mean_squared_log_error', 'normalized_mutual_info_score', 'positive_likelihood_ratio', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'r2', 'rand_score', 'recall', 'recall_macro', 'recall_micro', 'recall_samples'

In [30]:
test_predictions=ridge_cv_model.predict(X_test)

In [31]:
MAE=mean_absolute_error(y_test,test_predictions)

In [32]:
MSE=mean_squared_error(y_test,test_predictions)

In [33]:
RMSE=np.sqrt(MSE)

In [34]:
MAE

0.4273774884342007

In [35]:
MSE

0.38201298815376883

In [36]:
RMSE 

np.float64(0.6180719926948388)

In [37]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [38]:
## LASSO (Least absolute shrinkage and selection operator)

In [39]:
from sklearn.linear_model import LassoCV

In [40]:
lasso_cv_model=LassoCV(eps=0.1,n_alphas=100,cv=5)

In [41]:
lasso_cv_model.fit(X_train,y_train)

C:\Users\User\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:1622: FutureWarning: 'n_alphas' was deprecated in 1.7 and will be removed in 1.9. 'alphas' now accepts an integer value which removes the need to pass 'n_alphas'. The default value of 'alphas' will change from None to 100 in 1.9. Pass an explicit value to 'alphas' and leave 'n_alphas' to its default value to silence this warning.
  warnings.warn(


,eps,0.1
,n_alphas,100
,alphas,'warn'
,fit_intercept,True
,precompute,'auto'
,max_iter,1000
,tol,0.0001
,copy_X,True
,cv,5
,verbose,False
,n_jobs,None


In [42]:
lasso_cv_model.alpha_

np.float64(0.4943070909225828)

In [43]:
test_predictions=lasso_cv_model.predict(X_test)


In [44]:
MAE=mean_absolute_error(y_test,test_predictions)

In [45]:
MSE=mean_squared_error(y_test,test_predictions)

In [46]:
RMSE=np.sqrt(MSE)

In [47]:
MAE

0.6541723161252856

In [48]:
MSE

1.2787088713079853

In [49]:
RMSE

np.float64(1.1308001022762535)

In [50]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [51]:
from sklearn.linear_model import ElasticNetCV

In [57]:
elastic_model=ElasticNetCV(l1_ratio=[.1,.5,.7,.9,.95,1],eps=0.01,n_alphas=100,max_iter=1000000)

In [58]:
elastic_model.fit(X_train,y_train)

C:\Users\User\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:1622: FutureWarning: 'n_alphas' was deprecated in 1.7 and will be removed in 1.9. 'alphas' now accepts an integer value which removes the need to pass 'n_alphas'. The default value of 'alphas' will change from None to 100 in 1.9. Pass an explicit value to 'alphas' and leave 'n_alphas' to its default value to silence this warning.
  warnings.warn(


,l1_ratio,"[0.1, 0.5, ...]"
,eps,0.01
,n_alphas,100
,alphas,'warn'
,fit_intercept,True
,precompute,'auto'
,max_iter,1000000
,tol,0.0001
,cv,None
,copy_X,True
,verbose,0


In [60]:
elastic_model.l1_ratio_

np.float64(1.0)

In [61]:
test_predictions=elastic_model.predict(X_test)

In [62]:
MAE =mean_absolute_error(y_test,test_predictions)

In [63]:
MAE

0.5159788188265406